bolt repository
geodocgen/gopay pull request #1
Opened 2024-12-05 18:44 UTC by Anton-Kraev

2024-12-09 14:22 UTC, icyrogue requested changes
Про op для error handling'а какая была цель? Может быть я чего-то не понимаю?

2024-12-12 23:28 UTC, Anton-Kraev commented on internal/models/payment/payment.go
не понял прям в корень или в папку models в корне, вынес в папку models

2024-12-12 23:44 UTC, Anton-Kraev commented on internal/repository/bolt/link.go
> +	const op = "PaymentRepository.GetLink"
я думаю может так оставить
- вынес в константу op, чтобы не дублировать строки (например, GetLink) при каждом врапинге ошибки
- помимо функции еще указывается структура (PaymentRepository.GetLink), чтобы однозначно определять, где произошла ошибка, ведь у структур могут быть методы с одинаковыми названиями

2024-12-16 08:21 UTC, icyrogue commented on internal/models/payment/payment.go
я бы сделал прям в корень без папки

2025-02-22 22:53 UTC, closed without merging